### ISSUE TITLE
Consider using PBR

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#110]
As in https://github.com/openstack/oslo.config/blob/master/setup.py

**Comment by anxolerd** [comment]
@webknjaz: please add some description about what is PBR and what is our motivation to use it?

**Comment by webknjaz** [comment]
I hope it will help us keep all dependencies in one place. It's an OpenStack project: http://docs.openstack.org/developer/pbr/ / https://pypi.python.org/pypi/pbr / https://github.com/openstack-dev/pbr

**Comment by webknjaz** [comment]
https://blog.ionelmc.ro/presentations/packaging/

**Comment by webknjaz** [comment]
NOTE: now, consider using [pure setuptools>30.3](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)
