### ISSUE TITLE
Bad url for check-in handler in card template

### ISSUE THREAD

**Issue by anxolerd** [GDG-Ukraine/gdg.org.ua#114]
It is strange that there are two occurrences of `api` in url:

![image](https://cloud.githubusercontent.com/assets/6533582/18029610/5dd3eeae-6ca5-11e6-84fd-c1d43b8baadc.png)

**Comment by webknjaz** [comment]
not reproducible locally. perhaps needs re-deployment

**Comment by webknjaz** [comment]
not reproducible @ dev.gdg.org.ua as well

**Comment by webknjaz** [comment]
Fixed with re-deployment

**Comment by anxolerd** [comment]
:+1:
