### ISSUE TITLE
Use GitHub Projects?

### ISSUE THREAD

**Issue by unreadableusername** [GDG-Ukraine/gdg.org.ua#118]
GitHub has new awesome feature
Maybe it's better to use it?

**Comment by webknjaz** [comment]
We are considering this, but currently this means importing issues manually.

**Comment by unreadableusername** [comment]
It is too easy too import actually

**Comment by webknjaz** [comment]
I've tried using Projects for cherrypy repo, but it turned out to be a pain in the butt.
As for now, I'm happy with waffle.io
