### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#12]
Implement $sbj for registrations.

**Comment by anxolerd** [comment]
@webknjaz: what is this?

**Comment by webknjaz** [comment]
#39

**Comment by webknjaz** [comment]
Waitlist, I think.

**Comment by anxolerd** [comment]
not required for now, Closing.

**Comment by webknjaz** [comment]
why not?

**Comment by webknjaz** [comment]
Why not?

**Comment by anxolerd** [comment]
It cannot be implemented right now, and we will definitely forget about it when the following functionality will be implemented. Closing.
