### ISSUE TITLE
Hide some fields of registration form

### ISSUE THREAD

**Issue by olostan** [GDG-Ukraine/gdg.org.ua#15]
In ```event``` table there is field ``hidden`` with comma separated list of fields that should be not shown on this event registration form.

**Comment by webknjaz** [comment]
TODO: check whether this works on registration page front-end.
@OlexandrKovalchuk

**Comment by anxolerd** [comment]
@olostan see #33 and #34
For now `JSON` only supported

**Comment by webknjaz** [comment]
@anxolerd is this supported by form template?

**Comment by anxolerd** [comment]
@webknjaz at least it worked on my local setup.

**Comment by webknjaz** [comment]
Just follow the code and check all login

**Comment by anxolerd** [comment]
@webknjaz https://github.com/GDG-Ukraine/gdg.org.ua/blob/master/src/GDGUkraine/templates/register.html#L228-L235
I've noticed such wrapper around each field.

**Comment by webknjaz** [comment]
LGTM.
