### ISSUE TITLE
[FR] Mailing list

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#16]
Implement/choose/install $sbj.
Probably gmail acc with SMTP would be enough while we don't have huge amount attendees. It has 400 sent mails per day limit. However there are over 4000 in our DB.
That's a topic for discussions.

**Comment by webknjaz** [comment]
#26

**Comment by anxolerd** [comment]
Closing as duplicate of #26, which has more precise title.
