### ISSUE TITLE
UI bug during additional registration

### ISSUE THREAD

**Issue by zasadnyy** [GDG-Ukraine/gdg.org.ua#18]
There is no need to show "Registration is closing soon" during additional registration.
Screenshot http://monosnap.com/image/MxPrQ5CP7W9Lu6T5lHB0v6sTa
![Form screenshot](https://monosnap.com/file/MxPrQ5CP7W9Lu6T5lHB0v6sTa.png)

**Comment by webknjaz** [comment]
@bluebirrd what's your opinion?

**Comment by bluebirrd** [comment]
I think that it's absolutely unnecessary. Invitation link works regardless of form status.

**Comment by webknjaz** [comment]
@bluebirrd full answer plz, I didn't understand your point clearly.

**Comment by bluebirrd** [comment]
If you receive an invitation link for registration on the event, it works anyway, no matter if the form is closed for others at the moment or not. So, I think that showing the text "Registration is closing soon!" makes no sense and this element can me removed.

**Comment by webknjaz** [comment]
It's shown in case if there are less than 5 places left.

**Comment by bluebirrd** [comment]
OK, let's take a look at current situation. Registration to I/O Extended has already exceeded it's limit, but still I can generate an invitation code and send it to someone, so this person car register **even though** all the places are already taken. If the amount of available spots is (limit - registeredPeople), then for now it has negative value. If it is a negative integer, then we can assume that form is already closed. If it's closed, then it's not necessary to show the message "Registration is closing soon". 

I think that we can keep this element for global registration form, but there's no need to show it during additional registration via invites & so on.

(if I'm right about the counter of available spots, please fix it)

**Comment by webknjaz** [comment]
https://github.com/GDG-Ukraine/gdg.org.ua/blob/master/src/GDGUkraine/templates/register.html#L133-L137

**Comment by anxolerd** [comment]
@zasadnyy what did you mean saying _"during additional registration"_ ?
Did you mean "during registration by invite code" or "during registration opened again by exceeding max_regs value"?

@webknjaz I guess @bluebirrd meant, we should remove this banner if user tries to register via invite code. Probably we can do that by adding additional check on invite code.

**Comment by anxolerd** [comment]
# TODO:

> _I think that we can keep this element_ ["Registration is closing soon"] _for global registration form, but there's no need to show it during additional registration via invites & so on._
-- @bluebirrd
