### ISSUE TITLE
Fix adding custom field of type "Select"

### ISSUE THREAD

**Issue by cleac** [GDG-Ukraine/gdg.org.ua#23]
Now, when I add options to custom field of type "Select", they don't save. But it's really needed thing in such kind of registration form

**Comment by webknjaz** [comment]
I guess it's because of our yesterday's fixes w/ @OlexandrKovalchuk. Angular app doesn't initialize because of some syntax error. I'm checking this right now.

**Comment by webknjaz** [comment]
Fixed. (I think)
