### ISSUE TITLE
TODO: draw custom logo for GDG KPI

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#25]
$sbj.
/cc: @ValeryP

**Comment by ValeryP** [comment]
![gdg_kpi](https://cloud.githubusercontent.com/assets/3534020/7368135/c7442fc0-edad-11e4-9614-b14be28c91f5.png)

**Comment by ValeryP** [comment]
http://storage1.static.itmages.com/i/15/0428/h_1430218534_7348638_f05f211c08.png

**Comment by webknjaz** [comment]
@ValeryP plz commit it to https://github.com/GDG-Ukraine/gdg.org.ua/tree/master/static/img/logos

**Comment by webknjaz** [comment]
@ValeryP I've deployed this pic, but keep in mind it's not transparent and out-of-style.
