### ISSUE TITLE
Hidden fields are not supported

### ISSUE THREAD

**Issue by anxolerd** [GDG-Ukraine/gdg.org.ua#33]
There is no hidden fields support in regform.

My case:
```sql
MariaDB [gdg_db]> select hidden from gdg_events \G
*************************** 1. row ***************************
hidden: ["www", "company"]
```

![Image of form](http://ibin.co/26bXXNPuEEjf)

I suppose that happens because of [these lines] (https://github.com/GDG-Ukraine/gdg.org.ua/blob/master/src/GDGUkraine/model.py#L133-L160). There is no 'hidden' field in `SQLAlchemy` model.

**Comment by webknjaz** [comment]
Is this issue fixed?

**Comment by anxolerd** [comment]
It should be fixed now.
I'll be able to check it in the evening.

**Comment by anxolerd** [comment]
@webknjaz it seems this issue has been fixed=)

**Comment by webknjaz** [comment]
Plz refer the commit

**Comment by webknjaz** [comment]
This workaround should be reconsidered after merging `api-for-admin` into master

**Comment by anxolerd** [comment]
@webknjaz reconsiderations you mentioned and required refactorings will be done in separate task: 
https://github.com/GDG-Ukraine/gdg.org.ua/issues/50
