### ISSUE TITLE
Make async back-end Google+ Sign-In auth

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#40]
Doc: https://developers.google.com/identity/sign-in/web/backend-auth
https://developers.google.com/identity/sign-in/web/sign-in
#41

#79

**Comment by anxolerd** [comment]
Related to: https://github.com/GDG-Ukraine/gdg.org.ua/issues/6, https://github.com/GDG-Ukraine/gdg.org.ua/issues/11

**Comment by webknjaz** [comment]
Basically implemented
