### ISSUE TITLE
[Idea] Register visit button

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#44]
I think we may add a button called 'Record visit' or so to /card/{aes_hash} page visible for admins only.

Click on the button should call Admin API (see #72), which will trigger setting `EventParticipant.visited = True`.

This way we'll account event participants.

**Comment by anxolerd** [comment]
I like the idea, however I'm not sure about the implementation.

**Comment by webknjaz** [comment]
After merging `api-for-admin` it should be possible to check whether user is admin. What's the problem you're talking about?

**Comment by webknjaz** [comment]
@gora050 would you deal with this?

**Comment by gora050** [comment]
In progress +
