### ISSUE TITLE
Dependencies in setup.py

### ISSUE THREAD

**Issue by anxolerd** [GDG-Ukraine/gdg.org.ua#47]
I think there should be dependencies version in [`setup.py`](https://github.com/GDG-Ukraine/gdg.org.ua/blob/master/setup.py#L3) in order to prevent errors when some of dependencies receives major update which breaks the existing API.

What do you think about that?

**Comment by webknjaz** [comment]
You may test this approach. If it works without issues — go for it.

**Comment by anxolerd** [comment]
## Goal
Prevent dependency package update break this app.

## Problem
Now we have no version specified in `setup.py`. This means that the latest version of package will be downloaded and installed. However major updates often change a lot in package API, so there is a risk that one day such update will break gdg.org.ua project

## TODO:
1. Add dependencies versions to `setup.py`
2. Test if it would work without issues with packages given
3. If OK -- commit and push or PR else -- discard changes

**Comment by anxolerd** [comment]
Done in 72f52fc
Merged into [`api-for-admin`](https://github.com/GDG-Ukraine/gdg.org.ua/tree/api-for-admin) in f0c9da3
