### ISSUE TITLE
Dummy data in production

### ISSUE THREAD

**Issue by anxolerd** [GDG-Ukraine/gdg.org.ua#48]
# WTF is that?
Why there is a link to http://google.com titled as `Some testing event1234`?

**URL**: https://gdg.org.ua/events/54/register

![image](https://cloud.githubusercontent.com/assets/6533582/12362878/56d38bc4-bbce-11e5-9fed-7426cf2954ea.png)

**Comment by webknjaz** [comment]
`testing` flag of `Event` model isn't implemented in this repo.

**Comment by anxolerd** [comment]
@webknjaz why is it called `testing` ? Shouldn't it be called `show_in_upcoming_list`?

**Comment by webknjaz** [comment]
because @olostan called it this way.

**Comment by webknjaz** [comment]
Done
