### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#54]
e.g. Travis, Circle etc.

**Comment by anxolerd** [comment]
Please, provide, what should that CI do?
Just run codestyle check and tests? Or something more?

**Comment by webknjaz** [comment]
Yes, it should execute `pre-commit run --all-files` and run tests.
I think, we need `tox` here.
For now, the only test passing here is:

    NOSE_TESTCONFIG_AUTOLOAD_YAML=config/test/app.yml nosetests -w src/tests --tests=test_utils
I think, we should fix others first.

**Comment by anxolerd** [comment]
I'll do that

**Comment by webknjaz** [comment]
@anxolerd plz consider making flake8 ignore migrations by adding them to `tox.ini`. E.g. https://github.com/bluebirrd/nau-timetable/blob/master/tox.ini

Also plz configure `tox` to make running tests locally comfortable.
