### ISSUE TITLE
Feature flags

### ISSUE THREAD

**Issue by anxolerd** [GDG-Ukraine/gdg.org.ua#63]
I think, it would be convenient to have some system of enabling/disabling features quickly in production.

@webknjaz, @bluebirrd: what do you think about that?

**Comment by webknjaz** [comment]
This should be postponed and prioritized later.

**Comment by bluebirrd** [comment]
@anxolerd, nice idea, but I'm not sure about the urgency of doing this. I'll check out everything in here and tell you the priority in 1-2 days.

**Comment by webknjaz** [comment]
Closing in flavor of #120
