### ISSUE TITLE
Make nicer error handlers

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#66]
* [ ] Implement known error handlers
http://docs.cherrypy.org/en/latest/pkg/cherrypy.html?highlight=error_response#custom-error-handling

* [ ] Deal with unexpected error handler (how?)
https://github.com/GDG-Ukraine/gdg.org.ua/blob/api-for-admin/src/GDGUkraine/rest_controller.py#L527

* [ ] Traceback switch
https://bitbucket.org/cherrypy/cherrypy/src/da5e7fa6cb75acc0d03efcd16eb3266d790a9c6f/cherrypy/tutorial/tut10_http_errors.py?at=default&fileviewer=file-view-default#tut10_http_errors.py-57

**Comment by webknjaz** [comment]
Partially done for REST API.

**Comment by anxolerd** [comment]
Close as it was moved to #112
