### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by anxolerd** [GDG-Ukraine/gdg.org.ua#74]
## Objective
Protect project from being accidentally crashed with random commit.

## Problem
There are only 3 working tests in the repository. These are definitely too little to cover at least 50% of project's functionality. Hence there is a great possibility that random commit will break the application, cause there is no good way (manual testing is not a good way) to verify if nothing was broken.

## TODO
Design and implement test cases to cover project's functionality.

**Comment by webknjaz** [comment]
#53

**Comment by anxolerd** [comment]
Closed as duplicate
