### ISSUE TITLE
Run tests in vagga on CI

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#88]
Tox has some bugs which make testing of our project difficult. In #113 vagga containerization is being added alongside with tests in container. Probably it would be good to use them in CI.

~~https://github.com/ryanhiebert/tox-travis~~

**Comment by anxolerd** [comment]
I do not like tox at all. Especially its buggy templating system. I'd rather throw it away instead of applying new workarounds to make it work probably better.

**Comment by webknjaz** [comment]
Do you have any alternate suggestions of how to run tests in several environments?

**Comment by anxolerd** [comment]
[2016-08-27] update issue topic and description.

**Comment by webknjaz** [comment]
Done in #113
