### ISSUE TITLE
Little bugs in makefile

### ISSUE THREAD

**Issue by cleac** [GDG-Ukraine/gdg.org.ua#89]
## Problem
Found several bugs while building the project using `make`. The problem is on `make dev-deps` stage of building. Install fails
 - While installing bower - it wants for `npm -g install bower` be run under administrator privileges
 - While upgrading pip - the `pip install install --no-use-wheel -U -r -U pip` is called, while `pip install -U pip` must be

**Comment by webknjaz** [comment]
There's a recommendation about using `nvm` in README
