### ISSUE TITLE
Fix sending confirmation requests

### ISSUE THREAD

**Issue by bluebirrrrd** [GDG-Ukraine/gdg.org.ua#99]
# Issue
Each try to send confirmation emails returns an error: 
On page: `Something happen while approving, so some application could be not approved or notifications not sent.`
In console: 
`angular.min.js:106 POST http://reg.gdg.org.ua/api/events/55/send-confirm 500 (Internal Server Error)`

# Steps to reproduce
1. Open list of participants of some event
2. Select 1 or more participants
3. Click "Send confirmation email to {amount} participants"

## Additional info
Content of response:
```json
{ message: "Cannot read property 'google_oauth' of undefined",
stack: "TypeError: Cannot read property 'google_oauth' of undefined at Object.exports.createMailer (/app/server/card.js:86:29) at /app/server/api/gevents.js:170:23 at callbacks (/app/node_modules/express/lib/router/index.js:164:37) at param (/app/node_modules/express/lib/router/index.js:138:11) at param (/app/node_modules/express/lib/router/index.js:135:11) at pass (/app/node_modules/express/lib/router/index.js:145:5) at Router._dispatch (/app/node_modules/express/lib/router/index.js:173:5) at Object.router (/app/node_modules/express/lib/router/index.js:33:10) at next (/app/node_modules/connect/lib/proto.js:174:15) at Object.exports.restrictAdmin [as handle] (/app/server/auth.js:65:9) at next (/app/node_modules/connect/lib/proto.js:174:15) at pass (/app/node_modules/express/lib/router/index.js:110:24) at Router._dispatch (/app/node_modules/express/lib/router/index.js:173:5) at /app/node_modules/everyauth/index.js:47:16 at findUserById_callback (/app/node_modules/everyauth/index.js:108:5) at /app/server/auth.js:12:9"}
```

**Comment by webknjaz** [comment]
@bluebirrrrd this is not repo for deprecate NodeJS admin panel.

**Comment by anxolerd** [comment]
@webknjaz :

1. Until you release python admin for end user (I mean, when you inform users, that we have "brand new" admin console), [NodeJS admin](https://github.com/GDG-Ukraine/gdgregform) is not deprecated.
2. Behavior Anna reports might be caused by latest fixes, where credentials, which were hardcoded and pushed into this repository, were moved into config file. Probably config file was not updated  in production. Please, check it out.

/cc @bluebirrrrd

**Comment by webknjaz** [comment]
@anxolerd 
1) @bluebirrrrd is aware of new admin panel, which has this feature working, so she'll be able to use this feature
2.1) google credentials are stored as an environment variable (and I've replaced them back then, when Valentyn removed app key in Cloud Console)
2.2) If there were no credentials available to app nobody would be able to even log in, so it's not the case. It looks more like user session expiration.
